from typing import Any, Sequence, Mapping, Optional, Protocol

class _Trace(Protocol):
    ...

class Scatter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Figure:
    data: Sequence[_Trace]
    layout: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_trace(self, trace: Any) -> None: ...
    def update_layout(self, **kwargs: Any) -> 'Figure': ...
    def show(self, *args: Any, **kwargs: Any) -> None: ...
